version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mns_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mns_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mns_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  pgdata: